- name: install
  become: yes
  apt: pkg=git-core state=latest

- name: link global .gitignore
  file:
    src: "{{role_path}}/files/.gitignore-global"
    dest: "{{user_home}}/.gitignore-global"
    state: link
    force: yes

- name: update .gitconfig
  template:
    src: .gitconfig
    dest: "{{user_home}}/.gitconfig"
