#!/bin/bash

tmux_attach() {
  tmux -2 attach -dt "$1"
}
tmux_new() {
  tmux -2 new -s "$1"
}
tmux_kill_session() {
  tmux -2 kill-session -t "$1"
}
alias ta=tmux_attach
alias tl='tmux ls'
alias tn=tmux_new
alias tk=tmux_kill_session

alias mux=tmuxinator
