---

- name: add webupd8 repo
  apt_repository:
    repo: 'ppa:webupd8team/java'
  become: yes

- name: accept oracle license
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  become: yes

- name: install oracle-java8-installer
  apt: pkg={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - oracle-java8-set-default
    - ca-certificates
  become: yes
