#!/usr/bin/env python3

from urllib.request import urlopen
import json
def main():
    json_data_url = urlopen("http://ws.audioscrobbler.com/2.0/?method=user.getrecenttracks&user=chauney&api_key=dea841e75b7c112bb48959f7c1738f80&limit=1&extended=0&format=json")
    data = json_data_url.read().decode("utf-8")
    json_data = json.loads(data)

    last_track = json_data['recenttracks']['track'][0]
    artist = last_track['artist']['#text']
    album = last_track['album']['#text']
    title = last_track['name']
    last_played = '%s – %s – %s' % (artist, album, title)
    is_playing = '@attr' in last_track and last_track['@attr']['nowplaying'] == 'true';
    if not is_playing:
        date = last_track['date']['#text'];
        # sys.stderr.write('not currently playing anything, last track played "%s" at %s\n' % (last_played, date))
        print('')
    else:
        print(last_played)

if __name__ == '__main__':
    main()
