

# function install_vagrant() {
#   if ! command -v xmllint > /dev/null; then
#     sudo apt-get install libxml2-utils
#   fi
#   if ! command -v vagrant > /dev/null; then
#     VAGRANT_DEB_FILE="/tmp/vagrant.deb"
#     if [ ! -f "$VAGRANT_DEB_FILE" ]; then
#       deb_file_url="$(curl -sL "https://www.vagrantup.com/downloads.html" | xmllint --html --xpath "//a[contains(@href, 'x86_64.deb')]/@href" - 2> /dev/null | cut -d '"' -f2)"
#       echo "downloading '$deb_file_url' -> '$VAGRANT_DEB_FILE'"
#       curl -sLo "$VAGRANT_DEB_FILE" "$deb_file_url"
#     fi
#     echo "installing '$VAGRANT_DEB_FILE'"
#     sudo dpkg -i "$VAGRANT_DEB_FILE"
#   fi

# }

- name: download vagrant deb
  get_url: "https://releases.hashicorp.com/vagrant/1.9.7/vagrant_1.9.7_x86_64.deb"
  dest: /tmp/vagrant.deb

- name: install vagrant
  apt: deb=/tmp/vagrant.deb
  become: yes

