- hosts: localhost
  roles:
    - role: debug-environment
    - role: common-core-minimal
    - role: common-gui-minimal
    - role: ubuntu-overrides

    - role: gui-desktop-i3

    - role: virtualization-docker
