- hosts: localhost
  roles:
    - role: debug-environment
      tags: [ debug ]
    - role: common-core-minimal
      tags: [ core, minimal ]

    - role: development-java
      tags: [ development, java ]
    - role: development-maven
      tags: [ development, maven ]
    - role: development-clojure
      tags: [ development, clojure ]

    - role: virtualization-docker
      tags: [ virtualization, docker ]
