name: aoclj
root: /work/projects/personal/clojure/aoclj

windows:
  - code:
      layout: even-horizontal
      panes:
        - vim
        - vim
  - repl:
      layout: even-vertical
      panes:
        - lein test-refresh
        - lein repl
        - git status
