name: gameserver
root: <%= ENV["HOME"] %>

windows:
  - monitoring:
      layout: even-vertical
      panes:
        - htop
        - ls
  - starbound:
      layout: 6273,272x71,0,0[272x47,0,0{136x47,0,0,1,135x47,137,0,9},272x23,0,48,6]
      panes:
        - ~/services/starbound start; tail -Fn100 ~/steamcmd/starbound/storage/starbound_server.log
        - tail -Fn100 ~/steamcmd/starbound/storage/starbound_server.log | grep "Chat:\|RCON"
        - sleep 10; ~/services/starbound status
  - csgo:
      layout: even-vertical
      panes:
        - ~/services/csgo start
        - sleep 10; ~/services/csgo status
  - quake2:
      layout: even-vertical
      panes:
        - ~/services/quake2 start
        - sleep 10; ~/services/quake2 status
