# ~/.tmuxinator/wildfly.yml

name: wildfly
root: <%= ENV["WILDFLY_HOME"] %>

windows:
  - conf:
      layout: even-vertical
      panes:
        -
        -
  - logs:
      layout: even-vertical
      panes:
        - tail -Fn100 standalone/log/info.log
        - tail -Fn100 standalone/log/debug.log
  - files:
      layout: even-vertical
      panes:
        - mkdir -p /tmp/xmlexport && cd /tmp/xmlexport
