---

- name: remove old versions
  apt: pkg={{item}} state=absent
  with_items:
    - docker
    - docker-engine
    - docker.io

- name: add docker repository key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    keyserver: https://download.docker.com/linux/ubuntu/gpg
    state: present
  register: add_repository_key
  ignore_errors: true
  become: yes

- name: alternative | add docker repository key
  shell: "curl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
  when: add_repository_key|failed

- name: https apt transport
  apt: pkg=apt-transport-https state=present
  become: yes

- name: add docker repository and update apt cache
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ansible_lsb.id|lower}} {{ ansible_lsb.codename|lower }} stable"
    update_cache: yes
    state: present
  become: yes

- name: install docker package
  apt: pkg=docker-ce state=latest
  become: yes
