
- name: install tmux package
  apt: pkg=tmux state=latest
  become: yes


- name: ensure .config exists
  file:
    path: "{{user_home}}/.config"
    state: directory
    mode: '0755'

- name: link laio config directory
  file:
    src: "{{role_path}}/files/.config/laio"
    dest: "{{user_home}}/.config/laio"
    state: link
    force: yes

- name: link configuration
  file:
    src: "{{role_path}}/files/{{item}}"
    dest: "{{user_home}}/{{item}}"
    state: link
    force: yes
  with_items:
  - .tmux.conf


- name: source tmux aliases
  blockinfile:
    dest: "{{user_home}}/.aliases"
    marker: "# {mark} ANSIBLE MANAGED BLOCK tmux_aliases"
    create: yes
    # follow: yes
    block: |
      [[ -f "{{role_path}}/files/aliases" ]] && source "{{role_path}}/files/aliases"

