---

- name: download lein
  get_url:
    url: "https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein"
    dest: /usr/local/bin/lein
    mode: 0755
  become: yes

- name: make sure ~/.lein exists
  file:
    dest: ~/.lein
    state: directory

- name: link zsh config
  file:
    src: "{{ role_path}}/files/{{ item }}"
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items:
    - .lein/profiles.clj
