---

dependencies:
  - role: package-manager-sdkman

- name: install lein
  ansible.builtin.command: $HOME/.sdkman/bin/sdkman-init.sh && sdk install leiningen

- name: make sure ~/.lein exists
  file:
    dest: ~/.lein
    state: directory

- name: link ~/.lein/profiles.clj
  file:
    src: "{{ role_path}}/files/{{ item }}"
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items:
    - .lein/profiles.clj
