

# function install_virtualbox() {
#   if ! command -v virtualbox > /dev/null; then
#     echo "installing virtualbox"
#     sudo apt-get install virtualbox virtualbox-guest-utils
#   fi
# }
#
- name: install virtualbox
  apt: pkg={{item}} state=latest
  with_items:
    - virtualbox
    - virtualbox-guest-utils
    - virtualbox-guest-additions-iso
