- name: install core utility packages
  ansible.builtin.package:
    name:
      - tree
      - libxml2-utils
      - curl
      - mosh
      - jq
      - silversearcher-ag
      - progress
      - htop
    state: latest
  become: yes
